Release update  (#626)
* Update Github Release Info

* Actions release

* Update

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -53,6 +53,8 @@ jobs:
             echo "RELEASE=bleeding" >> $GITHUB_ENV
             echo "PRERELEASE=true" >> $GITHUB_ENV
           fi
+          TAG_NAME=${GITHUB_REF#refs/tags/}
+          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
       
       - name: Install
         run: ./scripts/linux/ci_install_core.sh
@@ -166,3 +168,31 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           tag_name: ${{ env.RELEASE }}
           files: projectGenerator-linux-armv7l-gui.gz
+
+      - name: Get Release ID for the Tag
+        id: get_release
+        if: github.repository == 'openframeworks/projectGenerator' && github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding')
+        run: |
+          RELEASE_ID=$(curl -s \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/openframeworks/projectGenerator/releases | jq -r '.[] | select(.tag_name=="${{ env.TAG_NAME }}") | .id')
+
+          if [ -z "$RELEASE_ID" ]; then
+            echo "Release ID not found for tag: ${{ env.TAG_NAME }}"
+            exit 1
+          fi
+
+          echo "RELEASE_ID=${RELEASE_ID}" >> $GITHUB_ENV
+          echo "Found Release ID: ${RELEASE_ID}"
+
+      - name: Update Release Description
+        if: github.repository == 'openframeworks/projectGenerator' && github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding')
+        run: |
+          curl -X PATCH \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/openframeworks/projectGenerator/releases/${{ env.RELEASE_ID }} \
+            -d '{
+              "body": "Updated release for tag: ${{ env.TAG_NAME }} - '"$(date '+%Y-%m-%d %H:%M:%S')"'"
+            }'
